struct SensorData {
  uint16_t idPacket;
  uint8_t  cansatId;
  float temperatureC;
  float pressureHpa;
  float altitudeM;
  float accelXmss;
  float accelYmss;
  float accelZmss;
  float rollDeg;
  float pitchDeg;
  float yawDeg;
  float ch0Voltage;
  float ch0Amps;
  float ch1Voltage;
  float ch1Amps;
  float ch2Voltage;
  float ch2Amps;
} data;
